### ISSUE TITLE
Streamlit link doesn't work

### ISSUE THREAD

**Issue by JaapBezemer** [pro-well-plan/opensource_apps#7]
When I click on the streamlit link it opens the streamlit site but instead of loading the app I get an error message.
![image](https://user-images.githubusercontent.com/94786753/153590855-7ec0be3b-9041-4a76-b781-a4a71fba4e8d.png)

**Comment by jcamiloangarita** [comment]
thanks @JaapBezemer for reporting. A fix was added and the site is back online.
